/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FindtransGridFrame.java
 *
 * Created on Aug 8, 2011, 4:27:26 PM
 */
package org.jakc.valetadmindesk.gui;

import javax.swing.JButton;
import org.jakc.valetadmindesk.controller.FindtransGridController;
import org.jakc.valetadmindesk.controller.InputtransFormController;
import org.openswing.swing.client.GridControl;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author wahhid
 */
public class FindtransGridFrame extends InternalFrame {

    private FindtransGridController gridController;
    /** Creates new form FindtransGridFrame */
    public FindtransGridFrame(FindtransGridController gridController) {        
        initComponents();
        this.gridController = gridController;
        this.gridControl1.setController(gridController);
        this.gridControl1.setGridDataLocator(gridController);
        this.comboColumn1.setDomain(this.gridController.getDomainController().getCBTranstype());
        this.comboColumn2.setDomain(this.gridController.getDomainController().getCBEmployee());
        this.comboColumn3.setDomain(this.gridController.getDomainController().getCBBooth());
        this.comboColumn4.setDomain(this.gridController.getDomainController().getCBEmployee());
        this.comboColumn5.setDomain(this.gridController.getDomainController().getCBEmployee());
        this.comboColumn6.setDomain(this.gridController.getDomainController().getCBBooth());
        this.comboColumn7.setDomain(this.gridController.getDomainController().getCBEmployee());
        this.comboColumn8.setDomain(this.gridController.getDomainController().getCBStatus());
        
    }

    public JButton getBtncorrection() {
        return btncorrection;
    }

    public GridControl getGridControl1() {
        return gridControl1;
    }
    
    
    

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reloadButton1 = new org.openswing.swing.client.ReloadButton();
        filterButton1 = new org.openswing.swing.client.FilterButton();
        exportButton1 = new org.openswing.swing.client.ExportButton();
        navigatorBar1 = new org.openswing.swing.client.NavigatorBar();
        btncorrection = new javax.swing.JButton();
        gridControl1 = new org.openswing.swing.client.GridControl();
        textColumn1 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn2 = new org.openswing.swing.table.columns.client.TextColumn();
        comboColumn1 = new org.openswing.swing.table.columns.client.ComboColumn();
        comboColumn8 = new org.openswing.swing.table.columns.client.ComboColumn();
        dateColumn1 = new org.openswing.swing.table.columns.client.DateColumn();
        dateTimeColumn1 = new org.openswing.swing.table.columns.client.DateTimeColumn();
        comboColumn2 = new org.openswing.swing.table.columns.client.ComboColumn();
        comboColumn3 = new org.openswing.swing.table.columns.client.ComboColumn();
        comboColumn4 = new org.openswing.swing.table.columns.client.ComboColumn();
        dateColumn2 = new org.openswing.swing.table.columns.client.DateColumn();
        dateTimeColumn2 = new org.openswing.swing.table.columns.client.DateTimeColumn();
        comboColumn5 = new org.openswing.swing.table.columns.client.ComboColumn();
        comboColumn6 = new org.openswing.swing.table.columns.client.ComboColumn();
        comboColumn7 = new org.openswing.swing.table.columns.client.ComboColumn();
        integerColumn1 = new org.openswing.swing.table.columns.client.IntegerColumn();
        integerColumn2 = new org.openswing.swing.table.columns.client.IntegerColumn();
        currencyColumn1 = new org.openswing.swing.table.columns.client.CurrencyColumn();

        setTitle("Transaction - Valet Admin");
        setUniqueInstance(true);

        btncorrection.setText("Correction");
        btncorrection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncorrectionActionPerformed(evt);
            }
        });

        gridControl1.setExportButton(exportButton1);
        gridControl1.setFilterButton(filterButton1);
        gridControl1.setFilterPanelOnGridPolicy(org.openswing.swing.util.java.Consts.FILTER_PANEL_ON_GRID_USE_CLOSE_BUTTON);
        gridControl1.setNavBar(navigatorBar1);
        gridControl1.setReloadButton(reloadButton1);
        gridControl1.setShowFilterPanelOnGrid(true);
        gridControl1.setValueObjectClassName("org.jakc.valetadmindesk.vo.Transvalet");
        gridControl1.getColumnContainer().setLayout(new java.awt.GridLayout(1, 0));

        textColumn1.setColumnFilterable(true);
        textColumn1.setColumnName("transid");
        textColumn1.setColumnSortable(true);
        gridControl1.getColumnContainer().add(textColumn1);

        textColumn2.setColumnFilterable(true);
        textColumn2.setColumnName("carnumber");
        textColumn2.setColumnSortable(true);
        gridControl1.getColumnContainer().add(textColumn2);

        comboColumn1.setColumnFilterable(true);
        comboColumn1.setColumnName("transtype");
        comboColumn1.setColumnSortable(true);
        gridControl1.getColumnContainer().add(comboColumn1);

        comboColumn8.setColumnFilterable(true);
        comboColumn8.setColumnName("status");
        comboColumn8.setColumnSortable(true);
        gridControl1.getColumnContainer().add(comboColumn8);

        dateColumn1.setColumnFilterable(true);
        dateColumn1.setColumnName("datein");
        dateColumn1.setColumnSortable(true);
        gridControl1.getColumnContainer().add(dateColumn1);

        dateTimeColumn1.setColumnFilterable(true);
        dateTimeColumn1.setColumnName("datetimein");
        dateTimeColumn1.setColumnSortable(true);
        gridControl1.getColumnContainer().add(dateTimeColumn1);

        comboColumn2.setColumnFilterable(true);
        comboColumn2.setColumnName("oprin");
        comboColumn2.setColumnSortable(true);
        gridControl1.getColumnContainer().add(comboColumn2);

        comboColumn3.setColumnFilterable(true);
        comboColumn3.setColumnName("boothin");
        comboColumn3.setColumnSortable(true);
        gridControl1.getColumnContainer().add(comboColumn3);

        comboColumn4.setColumnFilterable(true);
        comboColumn4.setColumnName("driverin");
        comboColumn4.setColumnSortable(true);
        gridControl1.getColumnContainer().add(comboColumn4);

        dateColumn2.setColumnFilterable(true);
        dateColumn2.setColumnName("dateout");
        dateColumn2.setColumnSortable(true);
        gridControl1.getColumnContainer().add(dateColumn2);

        dateTimeColumn2.setColumnFilterable(true);
        dateTimeColumn2.setColumnName("datetimeout");
        dateTimeColumn2.setColumnSortable(true);
        gridControl1.getColumnContainer().add(dateTimeColumn2);

        comboColumn5.setColumnFilterable(true);
        comboColumn5.setColumnName("oprout");
        comboColumn5.setColumnSortable(true);
        gridControl1.getColumnContainer().add(comboColumn5);

        comboColumn6.setColumnFilterable(true);
        comboColumn6.setColumnName("boothout");
        comboColumn6.setColumnSortable(true);
        gridControl1.getColumnContainer().add(comboColumn6);

        comboColumn7.setColumnFilterable(true);
        comboColumn7.setColumnName("driverout");
        comboColumn7.setColumnSortable(true);
        gridControl1.getColumnContainer().add(comboColumn7);

        integerColumn1.setColumnName("hours");
        gridControl1.getColumnContainer().add(integerColumn1);

        integerColumn2.setColumnName("minutes");
        gridControl1.getColumnContainer().add(integerColumn2);

        currencyColumn1.setColumnName("totalcharge");
        currencyColumn1.setCurrencySymbol("Rp");
        currencyColumn1.setCurrencySymbolOnLeft(false);
        gridControl1.getColumnContainer().add(currencyColumn1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gridControl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1203, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reloadButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exportButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncorrection, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 676, Short.MAX_VALUE)
                        .addComponent(navigatorBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navigatorBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reloadButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncorrection, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gridControl1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btncorrectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncorrectionActionPerformed
// TODO add your handling code here:
    new InputtransFormController(this.gridController.getAuth(),this.gridController.getVo().getTransid());    
}//GEN-LAST:event_btncorrectionActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncorrection;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn1;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn2;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn3;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn4;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn5;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn6;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn7;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn8;
    private org.openswing.swing.table.columns.client.CurrencyColumn currencyColumn1;
    private org.openswing.swing.table.columns.client.DateColumn dateColumn1;
    private org.openswing.swing.table.columns.client.DateColumn dateColumn2;
    private org.openswing.swing.table.columns.client.DateTimeColumn dateTimeColumn1;
    private org.openswing.swing.table.columns.client.DateTimeColumn dateTimeColumn2;
    private org.openswing.swing.client.ExportButton exportButton1;
    private org.openswing.swing.client.FilterButton filterButton1;
    private org.openswing.swing.client.GridControl gridControl1;
    private org.openswing.swing.table.columns.client.IntegerColumn integerColumn1;
    private org.openswing.swing.table.columns.client.IntegerColumn integerColumn2;
    private org.openswing.swing.client.NavigatorBar navigatorBar1;
    private org.openswing.swing.client.ReloadButton reloadButton1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn2;
    // End of variables declaration//GEN-END:variables
}
