/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReportViewer.java
 *
 * Created on Aug 12, 2011, 9:58:29 AM
 */
package org.jakc.valetadmindesk.gui;

import java.awt.BorderLayout;
import java.awt.Container;
import java.io.File;
import java.io.InputStream;
import java.util.HashMap;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.swing.JRViewer;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author wahhid
 */
public class ReportViewerFrame extends InternalFrame {

    /** Creates new form ReportViewer */
    public ReportViewerFrame(String filePath,HashMap parameters,JRDataSource dataSource) {
        System.out.println("Execute Report Viewer Frame");
        initComponents();
        try {             
            JasperPrint print = JasperFillManager.fillReport(filePath,parameters,dataSource);
            JRViewer viewer=new JRViewer(print);
            Container c=getContentPane();
            c.setLayout(new BorderLayout());
            c.add(viewer);
        } catch (JRException ex) {
            ex.printStackTrace();
        }               
    }
    
    public ReportViewerFrame(InputStream streamReport,HashMap parameters,JRDataSource dataSource) {
        System.out.println("Execute Report Viewer Frame");
        initComponents();
        try {                                    
            JasperPrint print = JasperFillManager.fillReport(streamReport,parameters,dataSource);
            JRViewer viewer=new JRViewer(print);
            Container c=getContentPane();
            c.setLayout(new BorderLayout());
            c.add(viewer);
        } catch (JRException ex) {
            ex.printStackTrace();
        }    
    }
    
    public ReportViewerFrame(JasperReport jasperReport,HashMap parameters,JRDataSource dataSource) {
        System.out.println("Execute Report Viewer Frame");
        initComponents();
        try {                                    
            
            JasperPrint print = JasperFillManager.fillReport(jasperReport,parameters,dataSource);
            JRViewer viewer=new JRViewer(print);
            Container c=getContentPane();
            c.setLayout(new BorderLayout());
            c.add(viewer);
        } catch (JRException ex) {
            ex.printStackTrace();
        }    
    }    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
