/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TransvaletcorrectionGridFrame.java
 *
 * Created on Feb 19, 2012, 9:03:43 AM
 */
package org.jakc.valetadmindesk.gui;

import org.jakc.valetadmindesk.controller.TransvaletcorrectionGridController;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author root
 */
public class TransvaletcorrectionGridFrame extends InternalFrame {

    private TransvaletcorrectionGridController gridController;
    /** Creates new form TransvaletcorrectionGridFrame */
    public TransvaletcorrectionGridFrame(TransvaletcorrectionGridController gridController) {
        this.gridController = gridController;
        initComponents();        
        setTitle("Transaction Correction - Valet Admin");
        this.gridControl1.setController(gridController);
        this.gridControl1.setGridDataLocator(gridController);
        this.comboColumn1.setDomain(this.gridController.getDomainController().getCBTranstype());
        this.comboColumn2.setDomain(this.gridController.getDomainController().getCBEmployee());
        this.comboColumn3.setDomain(this.gridController.getDomainController().getCBBooth());
        this.comboColumn4.setDomain(this.gridController.getDomainController().getCBEmployee());
        this.comboColumn5.setDomain(this.gridController.getDomainController().getCBEmployee());
        this.comboColumn6.setDomain(this.gridController.getDomainController().getCBBooth());
        this.comboColumn7.setDomain(this.gridController.getDomainController().getCBEmployee());        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reloadButton1 = new org.openswing.swing.client.ReloadButton();
        filterButton1 = new org.openswing.swing.client.FilterButton();
        exportButton1 = new org.openswing.swing.client.ExportButton();
        navigatorBar1 = new org.openswing.swing.client.NavigatorBar();
        gridControl1 = new org.openswing.swing.client.GridControl();
        textColumn1 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn2 = new org.openswing.swing.table.columns.client.TextColumn();
        comboColumn1 = new org.openswing.swing.table.columns.client.ComboColumn();
        dateTimeColumn1 = new org.openswing.swing.table.columns.client.DateTimeColumn();
        comboColumn2 = new org.openswing.swing.table.columns.client.ComboColumn();
        comboColumn3 = new org.openswing.swing.table.columns.client.ComboColumn();
        comboColumn4 = new org.openswing.swing.table.columns.client.ComboColumn();
        dateTimeColumn2 = new org.openswing.swing.table.columns.client.DateTimeColumn();
        comboColumn5 = new org.openswing.swing.table.columns.client.ComboColumn();
        comboColumn6 = new org.openswing.swing.table.columns.client.ComboColumn();
        comboColumn7 = new org.openswing.swing.table.columns.client.ComboColumn();

        gridControl1.setFilterPanelOnGridPolicy(org.openswing.swing.util.java.Consts.FILTER_PANEL_ON_GRID_USE_CLOSE_BUTTON);
        gridControl1.setShowFilterPanelOnGrid(true);
        gridControl1.setValueObjectClassName("org.jakc.valetadmindesk.vo.Transvaletcorrection");
        gridControl1.getColumnContainer().setLayout(new java.awt.GridLayout());

        textColumn1.setColumnFilterable(true);
        textColumn1.setColumnName("transid");
        textColumn1.setColumnSortable(true);
        gridControl1.getColumnContainer().add(textColumn1);

        textColumn2.setColumnFilterable(true);
        textColumn2.setColumnName("carnumber");
        textColumn2.setColumnSortable(true);
        gridControl1.getColumnContainer().add(textColumn2);

        comboColumn1.setColumnFilterable(true);
        comboColumn1.setColumnName("transtype");
        comboColumn1.setColumnSortable(true);
        gridControl1.getColumnContainer().add(comboColumn1);

        dateTimeColumn1.setColumnFilterable(true);
        dateTimeColumn1.setColumnName("datetimein");
        dateTimeColumn1.setColumnSortable(true);
        gridControl1.getColumnContainer().add(dateTimeColumn1);

        comboColumn2.setColumnFilterable(true);
        comboColumn2.setColumnName("oprin");
        comboColumn2.setColumnSortable(true);
        gridControl1.getColumnContainer().add(comboColumn2);

        comboColumn3.setColumnFilterable(true);
        comboColumn3.setColumnName("boothin");
        comboColumn3.setColumnSortable(true);
        gridControl1.getColumnContainer().add(comboColumn3);

        comboColumn4.setColumnFilterable(true);
        comboColumn4.setColumnName("driverin");
        comboColumn4.setColumnSortable(true);
        gridControl1.getColumnContainer().add(comboColumn4);

        dateTimeColumn2.setColumnFilterable(true);
        dateTimeColumn2.setColumnName("datetimeout");
        dateTimeColumn2.setColumnSortable(true);
        gridControl1.getColumnContainer().add(dateTimeColumn2);

        comboColumn5.setColumnFilterable(true);
        comboColumn5.setColumnName("oprout");
        comboColumn5.setColumnSortable(true);
        gridControl1.getColumnContainer().add(comboColumn5);

        comboColumn6.setColumnFilterable(true);
        comboColumn6.setColumnName("boothout");
        comboColumn6.setColumnSortable(true);
        gridControl1.getColumnContainer().add(comboColumn6);

        comboColumn7.setColumnFilterable(true);
        comboColumn7.setColumnName("driverout");
        comboColumn7.setColumnSortable(true);
        gridControl1.getColumnContainer().add(comboColumn7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gridControl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reloadButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exportButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 376, Short.MAX_VALUE)
                        .addComponent(navigatorBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navigatorBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reloadButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gridControl1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn1;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn2;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn3;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn4;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn5;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn6;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn7;
    private org.openswing.swing.table.columns.client.DateTimeColumn dateTimeColumn1;
    private org.openswing.swing.table.columns.client.DateTimeColumn dateTimeColumn2;
    private org.openswing.swing.client.ExportButton exportButton1;
    private org.openswing.swing.client.FilterButton filterButton1;
    private org.openswing.swing.client.GridControl gridControl1;
    private org.openswing.swing.client.NavigatorBar navigatorBar1;
    private org.openswing.swing.client.ReloadButton reloadButton1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn2;
    // End of variables declaration//GEN-END:variables
}
