/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VoucherdetailGridFrame.java
 *
 * Created on Sep 7, 2011, 1:35:24 PM
 */
package org.jakc.valetadmindesk.gui;

import org.jakc.valetadmindesk.controller.VoucherdetailGridController;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author wahhid
 */
public class VoucherdetailGridFrame extends InternalFrame {

    private VoucherdetailGridController controller;
    
    /** Creates new form VoucherdetailGridFrame */
    public VoucherdetailGridFrame(VoucherdetailGridController controller) {
        this.controller = controller;
        initComponents();
        this.gridControl1.setController(controller);
        this.gridControl1.setGridDataLocator(controller);
        this.comboColumn1.setDomain(this.controller.getDomainController().getCBEmployee());
        
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigatorBar1 = new org.openswing.swing.client.NavigatorBar();
        gridControl1 = new org.openswing.swing.client.GridControl();
        textColumn1 = new org.openswing.swing.table.columns.client.TextColumn();
        dateTimeColumn1 = new org.openswing.swing.table.columns.client.DateTimeColumn();
        checkBoxColumn1 = new org.openswing.swing.table.columns.client.CheckBoxColumn();
        dateTimeColumn2 = new org.openswing.swing.table.columns.client.DateTimeColumn();
        comboColumn1 = new org.openswing.swing.table.columns.client.ComboColumn();
        filterButton1 = new org.openswing.swing.client.FilterButton();
        reloadButton1 = new org.openswing.swing.client.ReloadButton();

        setUniqueInstance(true);

        gridControl1.setEditOnSingleRow(true);
        gridControl1.setFilterButton(filterButton1);
        gridControl1.setNavBar(navigatorBar1);
        gridControl1.setReloadButton(reloadButton1);
        gridControl1.setValueObjectClassName("org.jakc.valetadmindesk.vo.Voucherdetail");
        gridControl1.getColumnContainer().setLayout(new java.awt.GridLayout(1, 0));

        textColumn1.setColumnFilterable(true);
        textColumn1.setColumnName("vouchdetailid");
        textColumn1.setColumnSortable(true);
        gridControl1.getColumnContainer().add(textColumn1);

        dateTimeColumn1.setColumnFilterable(true);
        dateTimeColumn1.setColumnName("voucherusedate");
        dateTimeColumn1.setColumnSortable(true);
        gridControl1.getColumnContainer().add(dateTimeColumn1);

        checkBoxColumn1.setColumnFilterable(true);
        checkBoxColumn1.setColumnName("status");
        checkBoxColumn1.setColumnSortable(true);
        gridControl1.getColumnContainer().add(checkBoxColumn1);

        dateTimeColumn2.setColumnName("updateddate");
        gridControl1.getColumnContainer().add(dateTimeColumn2);

        comboColumn1.setColumnName("updatedby");
        gridControl1.getColumnContainer().add(comboColumn1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gridControl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reloadButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                        .addComponent(navigatorBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navigatorBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reloadButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gridControl1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.CheckBoxColumn checkBoxColumn1;
    private org.openswing.swing.table.columns.client.ComboColumn comboColumn1;
    private org.openswing.swing.table.columns.client.DateTimeColumn dateTimeColumn1;
    private org.openswing.swing.table.columns.client.DateTimeColumn dateTimeColumn2;
    private org.openswing.swing.client.FilterButton filterButton1;
    private org.openswing.swing.client.GridControl gridControl1;
    private org.openswing.swing.client.NavigatorBar navigatorBar1;
    private org.openswing.swing.client.ReloadButton reloadButton1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn1;
    // End of variables declaration//GEN-END:variables
}
